<<<<<<< HEAD
name = "v20250723"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true
=======
name = "60s"
main = "cf-worker.ts"
compatibility_date = "2025-01-15"
compatibility_flags = [ "nodejs_compat_v2" ]
>>>>>>> upstream/main
